/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications you make to this file will be overwritten the next time you run
 * the typegen command. Instead, adjust the input files that are used to generate it.
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityFileAsset = {
	_type: 'sanity.fileAsset';
	_id: string;
	_rev: string;
	_createdAt: string;
	_updatedAt: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type Page = {
	_id: string;
	_type: 'page';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	description?: string;
	metaImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	metaImageAlt?: string;
};

export type WebDocumentFields = {
	_type: 'webDocumentFields';
	title?: string;
	slug?: Slug;
	description?: string;
	metaImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	metaImageAlt?: string;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type SanityImageAsset = {
	_type: 'sanity.imageAsset';
	_id: string;
	_rev: string;
	_createdAt: string;
	_updatedAt: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

// Source: src/sanity/queries.ts

// Variable: allPagesQuery
// Query: *[_type == "page" && defined(slug.current)] | order(_createdAt asc) {    _id,    title,    slug,    description  }
export type AllPagesQueryResult = Array<{
	_id: string;
	title: string | null;
	slug: Slug | null;
	description: string | null;
}>;

// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    title,    slug,    description,    metaImage,    metaImageAlt  }
export type PageBySlugQueryResult = {
	_id: string;
	title: string | null;
	slug: Slug | null;
	description: string | null;
	metaImage: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
		};
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	} | null;
	metaImageAlt: string | null;
} | null;
