/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type BillboardLink = {
	text: string;
	url: string;
};

export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type MetaImage = {
	asset?: SanityImageAssetReference;
	media?: unknown; // Unable to locate the referenced type "media" in schema
	hotspot?: SanityImageHotspot;
	crop?: SanityImageCrop;
	_type: 'image';
};

export type RichText = {
	_type: 'richText';
	richText: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
		listItem?: 'bullet' | 'number';
		markDefs?: Array<{
			href: string;
			_type: 'portableTextLink';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
};

export type PersonReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'person';
};

export type PeopleRefs = {
	_type: 'peopleRefs';
	people: Array<
		{
			_key: string;
		} & PersonReference
	>;
};

export type ListScroller = {
	_type: 'listScroller';
	heading: string;
	body?: string;
	items: Array<string>;
};

export type Billboard = {
	_type: 'billboard';
	heading: string;
	body?: string;
	link?: BillboardLink;
	image?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
};

export type ImageObject = {
	_type: 'imageObject';
	image: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	alt?: string;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top: number;
	bottom: number;
	left: number;
	right: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x: number;
	y: number;
	height: number;
	width: number;
};

export type List = {
	_type: 'list';
	items: Array<string>;
};

export type Link = {
	_type: 'link';
	url: string;
	text: string;
};

export type BodyText = {
	_type: 'bodyText';
	text: string;
};

export type Subheading = {
	_type: 'subheading';
	text: string;
};

export type Heading = {
	_type: 'heading';
	text: string;
};

export type Blog = {
	_id: string;
	_type: 'blog';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	description?: string;
	metaImage?: MetaImage;
	metaImageAlt?: string;
	richText: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
		listItem?: 'bullet' | 'number';
		markDefs?: Array<{
			href: string;
			_type: 'portableTextLink';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
};

export type Person = {
	_id: string;
	_type: 'person';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name: string;
	bio: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal';
		listItem?: never;
		markDefs?: Array<{
			href: string;
			_type: 'bioLink';
			_key: string;
		}>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
	image: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: 'image';
	};
};

export type Page = {
	_id: string;
	_type: 'page';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	description?: string;
	metaImage?: MetaImage;
	metaImageAlt?: string;
	blocks: Array<
		| ({
				_key: string;
		  } & Billboard)
		| ({
				_key: string;
		  } & ListScroller)
		| ({
				_key: string;
		  } & PeopleRefs)
		| ({
				_key: string;
		  } & RichText)
	>;
};

export type Slug = {
	_type: 'slug';
	current: string;
	source?: string;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height: number;
	width: number;
	aspectRatio: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| BillboardLink
	| SanityImageAssetReference
	| MetaImage
	| RichText
	| PersonReference
	| PeopleRefs
	| ListScroller
	| Billboard
	| ImageObject
	| SanityImageCrop
	| SanityImageHotspot
	| List
	| Link
	| BodyText
	| Subheading
	| Heading
	| Blog
	| Person
	| Page
	| Slug
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;
